/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WithdrawRequestsRouteImport } from './routes/withdraw-requests'
import { Route as TournamentsRouteImport } from './routes/tournaments'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as MarketingPostsRouteImport } from './routes/marketing-posts'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndoorProfileRouteImport } from './routes/indoor-profile'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as IndexRouteImport } from './routes/index'

const WithdrawRequestsRoute = WithdrawRequestsRouteImport.update({
  id: '/withdraw-requests',
  path: '/withdraw-requests',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentsRoute = TournamentsRouteImport.update({
  id: '/tournaments',
  path: '/tournaments',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingPostsRoute = MarketingPostsRouteImport.update({
  id: '/marketing-posts',
  path: '/marketing-posts',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndoorProfileRoute = IndoorProfileRouteImport.update({
  id: '/indoor-profile',
  path: '/indoor-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bookings': typeof BookingsRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/indoor-profile': typeof IndoorProfileRoute
  '/login': typeof LoginRoute
  '/marketing-posts': typeof MarketingPostsRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/tournaments': typeof TournamentsRoute
  '/withdraw-requests': typeof WithdrawRequestsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bookings': typeof BookingsRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/indoor-profile': typeof IndoorProfileRoute
  '/login': typeof LoginRoute
  '/marketing-posts': typeof MarketingPostsRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/tournaments': typeof TournamentsRoute
  '/withdraw-requests': typeof WithdrawRequestsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bookings': typeof BookingsRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/indoor-profile': typeof IndoorProfileRoute
  '/login': typeof LoginRoute
  '/marketing-posts': typeof MarketingPostsRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/tournaments': typeof TournamentsRoute
  '/withdraw-requests': typeof WithdrawRequestsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bookings'
    | '/dashboard'
    | '/forgot-password'
    | '/indoor-profile'
    | '/login'
    | '/marketing-posts'
    | '/settings'
    | '/signup'
    | '/tournaments'
    | '/withdraw-requests'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bookings'
    | '/dashboard'
    | '/forgot-password'
    | '/indoor-profile'
    | '/login'
    | '/marketing-posts'
    | '/settings'
    | '/signup'
    | '/tournaments'
    | '/withdraw-requests'
  id:
    | '__root__'
    | '/'
    | '/bookings'
    | '/dashboard'
    | '/forgot-password'
    | '/indoor-profile'
    | '/login'
    | '/marketing-posts'
    | '/settings'
    | '/signup'
    | '/tournaments'
    | '/withdraw-requests'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookingsRoute: typeof BookingsRoute
  DashboardRoute: typeof DashboardRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  IndoorProfileRoute: typeof IndoorProfileRoute
  LoginRoute: typeof LoginRoute
  MarketingPostsRoute: typeof MarketingPostsRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  TournamentsRoute: typeof TournamentsRoute
  WithdrawRequestsRoute: typeof WithdrawRequestsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/withdraw-requests': {
      id: '/withdraw-requests'
      path: '/withdraw-requests'
      fullPath: '/withdraw-requests'
      preLoaderRoute: typeof WithdrawRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments': {
      id: '/tournaments'
      path: '/tournaments'
      fullPath: '/tournaments'
      preLoaderRoute: typeof TournamentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing-posts': {
      id: '/marketing-posts'
      path: '/marketing-posts'
      fullPath: '/marketing-posts'
      preLoaderRoute: typeof MarketingPostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/indoor-profile': {
      id: '/indoor-profile'
      path: '/indoor-profile'
      fullPath: '/indoor-profile'
      preLoaderRoute: typeof IndoorProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookingsRoute: BookingsRoute,
  DashboardRoute: DashboardRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  IndoorProfileRoute: IndoorProfileRoute,
  LoginRoute: LoginRoute,
  MarketingPostsRoute: MarketingPostsRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  TournamentsRoute: TournamentsRoute,
  WithdrawRequestsRoute: WithdrawRequestsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
